## Zorp Wiggles — Save / Load System (Phase 31: QoL)
## Autoload singleton that handles both manual save/load and automatic periodic
## saves. Captures the core run state (player stats, position, world seed,
## inventory, equipment, progression) to a JSON file in user://.
##
## Design:
##   - `save_game()` serializes the current run into a dictionary and writes it
##     to `user://zorp_save.json`. Safe to call any time (silently skips if the
##     game hasn't started or the player is dead/downed).
##   - `load_game()` reads the save file and applies the state back to the
##     relevant systems (GameManager, WeaponModSystem, EquipmentSystem,
##     PetStoneInventory, ProgressionSystem, PetStoneInventory, the player
##     node, the world generator's seed). Returns true on success.
##   - `has_save()` checks whether a save file exists.
##   - `delete_save()` removes the save file (called on death, NG+, etc.).
##   - Auto-save ticks every `AUTOSAVE_INTERVAL` seconds and on every biome
##     change. Auto-save is gated by `autosave_enabled` (default true) and can
##     be toggled from the settings menu or via the `toggle_autosave()` API.
##   - `save_version` is written into the file so future schema changes can
##     migrate or invalidate old saves gracefully.
##
## What is saved:
##   - Player: HP, max HP, XP, level, score, kills, best combo, position,
##     rotation yaw, current biome, world seed, game time.
##   - WeaponModSystem: material inventory, discovered mods, equipped mod.
##   - EquipmentSystem: rare materials, consumables, owned pieces + upgrade
##     levels, equipped pieces per slot.
##   - PetStoneInventory: stone counts.
##   - ProgressionSystem: skill ranks, skill points, prestige level.
##   - Active consumable effects (durations remaining) are NOT restored — they
##     are transient buffs and would be confusing to resume mid-effect.
##
## What is NOT saved:
##   - Live enemies, collectibles, projectiles (these are regenerated by the
##     world generator / spawner from the seed — the world is procedural).
##   - Cosmetic/character/accessibility settings (these have their own
##     persistence files already).
##   - Statistics (separate `user://zorp_stats.json` lifetime file).

extends Node

const SAVE_PATH: String = "user://zorp_save.json"
const SAVE_VERSION: int = 1
const AUTOSAVE_INTERVAL: float = 30.0  # seconds between auto-saves

signal game_saved()
signal game_loaded()
signal autosave_triggered()

# Auto-save state
var autosave_enabled: bool = true
var _autosave_timer: float = 0.0
var _has_pending_save: bool = false  # Set when a biome change requests a save


func _ready() -> void:
	# Auto-save on biome change — the player crossing into a new biome is a
	# natural checkpoint moment and gives the save file a meaningful "you are
	# here" anchor. We connect with a deferred call so the biome change
	# (which emits from GameManager._process) doesn't stall the frame.
	if GameManager:
		GameManager.biome_changed.connect(_on_biome_changed)
		GameManager.player_died.connect(_on_player_died)
		GameManager.game_restarted.connect(_on_game_restarted)


func _process(delta: float) -> void:
	if not autosave_enabled:
		return
	if not GameManager or not GameManager.player_is_alive:
		return
	# Only auto-save during an active run (not in menus / before game start).
	if GameManager.game_time < 5.0:
		return  # Wait at least 5s into a run before the first auto-save
	_autosave_timer += delta
	if _autosave_timer >= AUTOSAVE_INTERVAL:
		_autosave_timer = 0.0
		_do_autosave()
	# If a biome change requested a save and at least 2s have passed since the
	# last save, save now (debounced so rapid biome hopping doesn't thrash).
	if _has_pending_save:
		_has_pending_save = false
		_do_autosave()


func _do_autosave() -> void:
	if save_game():
		autosave_triggered.emit()


# ── Public API ──────────────────────────────────────────────────────────────

## Returns true if a save file exists on disk.
func has_save() -> bool:
	return FileAccess.file_exists(SAVE_PATH)


## Get the save timestamp (as a Unix epoch seconds string) for display in
## the load menu. Returns "" if no save or unreadable.
func get_save_timestamp() -> String:
	if not has_save():
		return ""
	var f := FileAccess.open(SAVE_PATH, FileAccess.READ)
	if not f:
		return ""
	var text := f.get_as_text()
	f.close()
	var data = JSON.parse_string(text)
	if typeof(data) != TYPE_DICTIONARY:
		return ""
	return String(data.get("timestamp", ""))


## Get a short summary string for the load menu (level, score, biome, time).
func get_save_summary() -> String:
	if not has_save():
		return "No save file"
	var f := FileAccess.open(SAVE_PATH, FileAccess.READ)
	if not f:
		return "No save file"
	var text := f.get_as_text()
	f.close()
	var data = JSON.parse_string(text)
	if typeof(data) != TYPE_DICTIONARY:
		return "Corrupt save"
	var lvl: int = int(data.get("player_level", 1))
	var score: int = int(data.get("player_score", 0))
	var biome_name: String = String(data.get("biome_name", "Unknown"))
	var time_str: String = _format_time(float(data.get("game_time", 0.0)))
	return "Lv %d  |  %s  |  %s  |  %s" % [lvl, biome_name, time_str, get_save_timestamp()]


## Save the current game state to disk. Returns true on success.
## Silently returns false if the game hasn't started or the player is dead.
func save_game() -> bool:
	if not GameManager:
		return false
	if not GameManager.player_is_alive and not GameManager.player_is_downed:
		return false  # Dead-and-done state — don't save a corpse
	if GameManager.game_time < 1.0:
		return false  # Game hasn't really started yet
	var data := _collect_state()
	var f := FileAccess.open(SAVE_PATH, FileAccess.WRITE)
	if not f:
		push_warning("[SaveSystem] Could not open save file for writing")
		return false
	f.store_string(JSON.stringify(data, "  "))
	f.close()
	game_saved.emit()
	return true


## Load the saved game state and apply it. Returns true on success.
## The caller is responsible for triggering a world reload / player respawn
## after this — `load_game()` only restores the *data*, it does not rebuild
## the world or move the player (that requires a scene reload to re-seed
## the world generator). Use `load_and_restart()` for the full flow.
func load_game() -> bool:
	if not has_save():
		return false
	var f := FileAccess.open(SAVE_PATH, FileAccess.READ)
	if not f:
		return false
	var text := f.get_as_text()
	f.close()
	var data = JSON.parse_string(text)
	if typeof(data) != TYPE_DICTIONARY:
		push_warning("[SaveSystem] Save file is corrupt or empty")
		return false
	var version: int = int(data.get("version", 0))
	if version != SAVE_VERSION:
		push_warning("[SaveSystem] Save version mismatch (got %d, expected %d) — ignoring" % [version, SAVE_VERSION])
		return false
	_apply_state(data)
	game_loaded.emit()
	return true


## Full load flow: apply the save data, then request a scene reload so the
## world regenerates with the saved seed and the player spawns at the saved
## position. This is what the "Continue" button in the main menu calls.
## Returns true if a save was loaded and a reload was requested.
func load_and_restart() -> bool:
	if not load_game():
		return false
	# Mark that we want to restore position after the scene reloads —
	# GameManager._start_game() runs on the new scene and would reset
	# state, so we stash a "pending restore" flag the new scene reads.
	# We use a meta flag on the autoload itself (survives the scene change).
	set_meta("_pending_restore", true)
	# Reload the main scene to regenerate the world with the saved seed.
	get_tree().change_scene_to_file("res://scenes/main.tscn")
	return true


## Delete the save file. Called on death (so the player can't reload a
## dead run) and on explicit "new game" from the menu.
func delete_save() -> void:
	if has_save():
		DirAccess.remove_absolute(SAVE_PATH)


## Toggle auto-save on/off. Returns the new state.
func toggle_autosave() -> bool:
	autosave_enabled = not autosave_enabled
	return autosave_enabled


## Set auto-save explicitly (for the settings menu toggle).
func set_autosave(enabled: bool) -> void:
	autosave_enabled = enabled


# ── State collection ────────────────────────────────────────────────────────

func _collect_state() -> Dictionary:
	var data := {}
	data["version"] = SAVE_VERSION
	data["timestamp"] = Time.get_datetime_string_from_system(false, true)
	# ── Player core state ──
	data["player_hp"] = GameManager.player_hp
	data["player_max_hp"] = GameManager.player_max_hp
	data["player_xp"] = GameManager.player_xp
	data["player_xp_to_next"] = GameManager.player_xp_to_next
	data["player_level"] = GameManager.player_level
	data["player_score"] = GameManager.player_score
	data["player_kills"] = GameManager.player_kills
	data["player_best_combo"] = GameManager.player_best_combo
	data["player_total_pickups"] = GameManager.player_total_pickups
	data["current_biome"] = GameManager.current_biome
	data["world_seed"] = GameManager.world_seed
	data["game_time"] = GameManager.game_time
	# Biome name for the save summary (display only)
	data["biome_name"] = _biome_name(GameManager.current_biome)
	# ── Player position + rotation ──
	if GameManager.player and is_instance_valid(GameManager.player):
		data["player_pos_x"] = GameManager.player.global_position.x
		data["player_pos_y"] = GameManager.player.global_position.y
		data["player_pos_z"] = GameManager.player.global_position.z
		data["player_yaw"] = GameManager.player.rotation_degrees.y
	# ── Weapon mod system ──
	if WeaponModSystem:
		data["wms_inventory"] = WeaponModSystem.get_inventory()
		data["wms_discovered"] = WeaponModSystem.get_discovered_mods()
		data["wms_equipped"] = WeaponModSystem.get_equipped_mod()
	# ── Equipment system ──
	if EquipmentSystem:
		data["eq_rare_materials"] = EquipmentSystem.get_rare_material_inventory()
		data["eq_consumables"] = EquipmentSystem.get_consumable_inventory()
		data["eq_owned_pieces"] = EquipmentSystem.get_owned_pieces_dict()
		data["eq_equipped"] = [
			EquipmentSystem.get_equipped_piece(0),
			EquipmentSystem.get_equipped_piece(1),
			EquipmentSystem.get_equipped_piece(2),
		]
	# ── Pet stone inventory ──
	if PetStoneInventory:
		data["pet_stones"] = PetStoneInventory.get_inventory()
	# ── Progression system ──
	if ProgressionSystem:
		data["prog_skill_ranks"] = ProgressionSystem.get_all_skill_ranks()
		data["prog_skill_points"] = ProgressionSystem.get_skill_points()
		data["prog_prestige"] = ProgressionSystem.get_prestige_level()
	return data


# ── State application ───────────────────────────────────────────────────────

func _apply_state(data: Dictionary) -> void:
	# ── Player core state ──
	GameManager.player_hp = int(data.get("player_hp", GameManager.player_hp))
	GameManager.player_max_hp = int(data.get("player_max_hp", GameManager.player_max_hp))
	GameManager.player_xp = int(data.get("player_xp", 0))
	GameManager.player_xp_to_next = int(data.get("player_xp_to_next", GameConstants.PLAYER_START_XP))
	GameManager.player_level = int(data.get("player_level", 1))
	GameManager.player_score = int(data.get("player_score", 0))
	GameManager.player_kills = int(data.get("player_kills", 0))
	GameManager.player_best_combo = int(data.get("player_best_combo", 0))
	GameManager.player_total_pickups = int(data.get("player_total_pickups", 0))
	GameManager.current_biome = int(data.get("current_biome", GameConstants.Biome.GRASS))
	GameManager.world_seed = int(data.get("world_seed", GameManager.world_seed))
	GameManager.game_time = float(data.get("game_time", 0.0))
	# Emit signals so the HUD updates immediately
	GameManager.hp_changed.emit(GameManager.player_hp, GameManager.player_max_hp)
	GameManager.xp_changed.emit(GameManager.player_xp, GameManager.player_xp_to_next)
	GameManager.score_changed.emit(GameManager.player_score)
	# ── Weapon mod system ──
	if WeaponModSystem and data.has("wms_inventory"):
		WeaponModSystem.set_inventory(data["wms_inventory"])
		var discovered: Array = data.get("wms_discovered", [GameConstants.WeaponMod.NONE])
		WeaponModSystem.set_discovered_mods(discovered)
		var equipped: int = int(data.get("wms_equipped", GameConstants.WeaponMod.NONE))
		WeaponModSystem.set_equipped_mod(equipped)
	# ── Equipment system ──
	if EquipmentSystem and data.has("eq_rare_materials"):
		EquipmentSystem.set_rare_material_inventory(data["eq_rare_materials"])
		EquipmentSystem.set_consumable_inventory(data.get("eq_consumables", {}))
		EquipmentSystem.set_owned_pieces(data.get("eq_owned_pieces", {}))
		var eq_equipped: Array = data.get("eq_equipped", [-1, -1, -1])
		EquipmentSystem.set_equipped_pieces(eq_equipped)
	# ── Pet stone inventory ──
	if PetStoneInventory and data.has("pet_stones"):
		PetStoneInventory.set_inventory(data["pet_stones"])
	# ── Progression system ──
	if ProgressionSystem and data.has("prog_skill_ranks"):
		ProgressionSystem.set_all_skill_ranks(data["prog_skill_ranks"])
		ProgressionSystem.set_skill_points(int(data.get("prog_skill_points", 0)))
		ProgressionSystem.set_prestige_level(int(data.get("prog_prestige", 0)))
	# Stash position for the new scene to read after it loads
	if data.has("player_pos_x"):
		set_meta("_restore_pos", Vector3(
			float(data["player_pos_x"]),
			float(data["player_pos_y"]),
			float(data["player_pos_z"])
		))
		set_meta("_restore_yaw", float(data.get("player_yaw", 0.0)))


## Called by the player's _ready (via GameManager) after the scene reloads to
## restore the saved position. Returns true if a position was restored.
func try_restore_player_position(player: Node) -> bool:
	if not has_meta("_restore_pos"):
		return false
	var pos: Vector3 = get_meta("_restore_pos")
	var yaw: float = float(get_meta("_restore_yaw"))
	player.global_position = pos
	player.rotation_degrees.y = yaw
	# Clear the meta so a subsequent fresh start doesn't restore
	remove_meta("_restore_pos")
	remove_meta("_restore_yaw")
	return true


## Called by GameManager after _start_game() to apply a pending save restore.
## Returns true if the run state was restored from a save (and the normal
## _start_game reset should be partially skipped).
func consume_pending_restore() -> bool:
	if has_meta("_pending_restore"):
		remove_meta("_pending_restore")
		return true
	return false


# ── Signal handlers ──────────────────────────────────────────────────────────

func _on_biome_changed(_biome_id: int) -> void:
	# Debounced save on biome change — set the pending flag; _process will
	# pick it up and save within the next frame (avoiding a save every time
	# the player skitters across a biome border).
	_has_pending_save = true


func _on_player_died() -> void:
	# Delete the save on death so the player can't reload a dead run.
	# (Permadeath-ish: the run is over, start fresh next time.)
	delete_save()


func _on_game_restarted() -> void:
	# A fresh restart (e.g. from the death screen "Try Again") should not
	# carry over the old save. The new run will auto-save as it progresses.
	_autosave_timer = 0.0
	_has_pending_save = false


# ── Helpers ──────────────────────────────────────────────────────────────────

func _biome_name(biome_id: int) -> String:
	# GameConstants.BIOME_NAMES is an Array[String] indexed by Biome enum.
	if GameConstants.BIOME_NAMES and biome_id >= 0 and biome_id < GameConstants.BIOME_NAMES.size():
		return GameConstants.BIOME_NAMES[biome_id]
	return "Unknown"


func _format_time(t: float) -> String:
	var mins: int = int(t) / 60
	var secs: int = int(t) % 60
	return "%d:%02d" % [mins, secs]